import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
const read = (path) => readFileSync(path, 'utf8');
const header = read('src/components/Header.tsx'); const footer = read('src/components/Footer.tsx');
const home = read('src/pages/HomePage.tsx'); const brand = read('src/components/BrandLogo.tsx');
const banner = read('src/components/TelegramBanner.tsx'); const links = read('src/data/publicLinks.ts');
const index = read('index.html'); const favicon = read('public/favicon.svg'); const logo = read('public/telvora-logo.svg');
assert.match(header, /<Tv className="w-5 h-5 text-white" strokeWidth=\{2\.5\}/); assert.match(header, /w-9 h-9 rounded-xl bg-gradient-to-br from-accent-500 to-accent-700/); assert.match(header, /to="\/" aria-label="TELVORA — на главную"/);
assert.match(footer, /<Tv className="w-7 h-7 text-white" strokeWidth=\{2\.5\}/); assert.match(footer, /w-12 h-12 rounded-xl bg-gradient-to-br from-accent-500 to-accent-700/); assert.match(footer, /to="\/" aria-label="TELVORA — на главную"/);
assert.match(brand, /telvora-mark\.svg/); assert.doesNotMatch(brand, /telvora-logo\.svg|TELVORA|dark:bg-white/);
assert.doesNotMatch(brand, /telvora-logo-white\.svg/);
assert.doesNotMatch(header + footer, /<BrandLogo|telvora-mark\.svg/);
assert.match(logo, /viewBox="0 0 520 130"/); assert.match(logo, /ПРЕМИАЛЬНЫЕ ТЕЛЕВИЗОРЫ И ЭЛЕКТРОНИКА/);
assert.match(logo, /fill="#FF6A00"/); assert.doesNotMatch(logo, /clip-path|overflow="hidden"/);
assert.match(index, /href="\/favicon\.svg"/); assert.match(favicon, /#FF6A00/); assert.doesNotMatch(favicon, />T<\/text>/);
assert.ok(home.indexOf('<TelegramBanner />') > home.indexOf('<ProductGrid')); assert.ok(home.indexOf('<TelegramBanner />') < home.indexOf('<TechSection'));
assert.match(links, /https:\/\/t\.me\/telvora_store/); assert.match(links, /https:\/\/t\.me\/telvora_reviews/);
assert.equal((banner.match(/target="_blank"/g) ?? []).length, 2); assert.equal((banner.match(/rel="noopener noreferrer"/g) ?? []).length, 2);
console.log('Brand/logo, favicon and Telegram frontend contract: PASS');
