import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import ts from 'typescript';
const source=fs.readFileSync(new URL('../src/pages/catalogModelFilters.ts',import.meta.url),'utf8');
const compiled=ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020}}).outputText;
const module={exports:{}}; vm.runInNewContext(compiled,{module,exports:module.exports},{filename:'catalogModelFilters.ts'});
const {getModelGroups,getModelGroup,getTechnology,getFilterOptions,filterCatalogProducts}=module.exports;
const product=(id,overrides={})=>({id:String(id),slug:`tv-${id}`,name:`TV ${id}`,brand:'LG',series:'C5',category:'OLED',screenSize:'55',resolution:'3840 × 2160 (4K UHD)',price:0,rating:5,reviews:0,description:'',specs:[],highlights:[],variants:[{price:120000,isActive:true}],...overrides});
const products=[product(1),product(2,{brand:' lg ',series:' C5 '}),product(3,{brand:'Samsung',series:'S90F',category:'QLED',screenSize:'65',price:90000,variants:[]}),product(4,{brand:'Samsung',series:'Q900',category:'8K',resolution:'7680 × 4320 (8K UHD)'}),product(5,{brand:undefined,series:'Unknown'})];
const groups=getModelGroups(products); assert.equal(JSON.stringify(groups.map(g=>[g.label,g.count])),JSON.stringify([['LG C5',2],['Samsung Q900',1],['Samsung S90F',1]]));
assert.equal(getModelGroup(products[4]),null,'ambiguous item remains in all-products fallback');
assert.equal(getTechnology(products[3]),'','8K is not misclassified as display technology');
assert.equal(JSON.stringify(getFilterOptions(products,p=>p.resolution)),JSON.stringify(['3840 × 2160 (4K UHD)','7680 × 4320 (8K UHD)']));
const state={modelKey:groups[0].key,brands:['LG'],sizes:['55'],resolutions:['3840 × 2160 (4K UHD)'],technologies:['OLED'],minPrice:'110000',maxPrice:'130000',sort:'price-asc'};
assert.equal(JSON.stringify(filterCatalogProducts(products,state).map(p=>p.id)),JSON.stringify(['1','2']),'model and filters combine using published variant minimum');
assert.equal(filterCatalogProducts(products,{...state,resolutions:['7680 × 4320 (8K UHD)']}).length,0,'empty combination returns no products');
assert.equal(filterCatalogProducts(products,{modelKey:'',brands:[],sizes:[],resolutions:[],technologies:[],minPrice:'',maxPrice:'',sort:'default'}).length,5,'reset state restores every product');
console.log('PASS catalog model grouping and combined filters');
