<?php
declare(strict_types=1);
use Dompdf\Dompdf;
use Dompdf\Options;
function check(bool $ok,string $message):void{if(!$ok)throw new RuntimeException($message);}
$root=dirname(__DIR__);$source=(string)file_get_contents($root.'/generate_invoice_pdf.php');
foreach(['<th>Наименование</th>','table-header-group','page-break-inside: avoid','class="final-block"','Доставка — стоимость согласовывается','min_screen_size','sellerRegistrationDate','sellerBankAccount','sellerVatNotice'] as $needle)check(str_contains($source,$needle),"generator missing {$needle}");
check(!str_contains($source,'<h3>Сервисные услуги</h3>'),'separate service table remains');
check(!str_contains($source,'position: fixed'),'footer must stay inside final block');
check(!str_contains($source,'Багратионовский'),'fake seller address remains');
check(str_contains($source,'SELECT service_name,television_name,screen_size,unit_price,quantity,total,metadata FROM order_services'),'service snapshot query incomplete');
check(!str_contains($source,'FROM service_catalog'),'invoice reads current service prices');
$autoload=getenv('TELVORA_TEST_AUTOLOAD');check(is_string($autoload)&&is_file($autoload),'TELVORA_TEST_AUTOLOAD is required');require $autoload;
$css='@page{margin:18mm 15mm}body{font-family:DejaVu Sans,sans-serif;font-size:10px}table{width:100%;border-collapse:collapse}.info td,.rows td,.rows th{border:1px solid #222;padding:5.5px 6px}.info{margin-top:9px}.seller{font-size:8.5px;line-height:1.3}.rows{margin-top:12px}.rows thead{display:table-header-group}.rows tr,.final{page-break-inside:avoid;break-inside:avoid}.final{margin-top:8px}.signatures{margin-top:18px}';
function fixture(string $css,int $products,array $services,bool $pending,float $delivery):string{$rows='';$n=1;$total=0;for($i=1;$i<=$products;$i++,$n++){$price=100000+$i;$total+=$price;$rows.="<tr><td>{$n}</td><td>Телевизор {$i}</td><td>1</td><td>{$price} ₽</td><td>{$price} ₽</td></tr>";}foreach($services as [$name,$price]){$total+=$price;$rows.="<tr><td>{$n}</td><td>{$name}</td><td>1</td><td>{$price} ₽</td><td>{$price} ₽</td></tr>";$n++;}if($pending){$rows.="<tr><td>{$n}</td><td>Доставка — стоимость согласовывается</td><td>1</td><td>—</td><td>—</td></tr>";$totalText='После согласования доставки';}else{$total+=$delivery;$rows.="<tr><td>{$n}</td><td>Доставка</td><td>1</td><td>{$delivery} ₽</td><td>{$delivery} ₽</td></tr>";$totalText="{$total} ₽";}return '<html lang="ru"><meta charset="UTF-8"><style>'.$css.'</style><body><h2>ТОВАРНАЯ НАКЛАДНАЯ</h2><table class="info"><tr><td>Продавец</td><td class="seller">ИП Помякшев Иван Владимирович · ИНН 500907422390 · ОГРНИП 326508100533649<br>Дата регистрации: 09.09.2026<br>ПАО Сбербанк · р/с 40802810640070063020 · БИК 044525225 · к/с 30101810400000000225</td></tr><tr><td>Контакты</td><td>+7 (926) 202-01-19 · telvora24gmail.com / telvorasupport24gmail.com</td></tr><tr><td>НДС</td><td class="seller">НДС не предъявляется в связи с освобождением от исполнения обязанностей налогоплательщика НДС в соответствии со ст. 145 НК РФ.</td></tr></table><table class="rows"><thead><tr><th>№</th><th>Наименование</th><th>Кол-во</th><th>Цена</th><th>Сумма</th></tr></thead><tbody>'.$rows.'</tbody></table><div class="final"><b>ИТОГО: '.$totalText.'</b><p>Проверка товара не ограничивает законные права покупателя.</p><table class="signatures"><tr><td>Продавец __________________</td><td>Покупатель __________________</td></tr></table><p>TELVORA</p></div></body></html>';}
$fixtures=['one-product'=>[1,[],false,2000],'product-service'=>[1,[['Монтаж телевизора',12000]],false,2000],'delivery'=>[2,[],false,2000],'long-order'=>[42,array_fill(0,8,['Монтаж телевизора',12000]),false,2000],'pending-delivery'=>[1,[['Монтаж телевизора',7000]],true,0]];
foreach($fixtures as $name=>[$products,$services,$pending,$delivery]){$pdf=new Dompdf(new Options());$pdf->loadHtml(fixture($css,$products,$services,$pending,$delivery),'UTF-8');$pdf->setPaper('A4');$pdf->render();$pages=$pdf->getCanvas()->get_page_count();check($name==='long-order'?$pages>=2:$pages===1,"{$name}: {$pages} pages");echo "FIXTURE {$name}: {$pages} page(s)\n";}
echo "INVOICE COMPACT LAYOUT FIXTURES PASSED\n";
