import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';

const workflow = await readFile(new URL('../.github/workflows/seo-autopublish.yml', import.meta.url), 'utf8');
const worker = await readFile(new URL('../seo_publication_worker.php', import.meta.url), 'utf8');
const publicationService = await readFile(new URL('../seo_publication_service.php', import.meta.url), 'utf8');

assert.match(workflow, /on:\r?\n\s+workflow_dispatch:/);
assert.match(workflow, /schedule:\r?\n\s+- cron: ['"]\*\/5 \* \* \* \*['"]/);
assert.doesNotMatch(workflow, /^\s+(push|pull_request|workflow_run|repository_dispatch):/m);
assert.match(workflow, /concurrency:\r?\n\s+group: telvora-seo-autopublish-production\r?\n\s+cancel-in-progress: false/);
assert.match(workflow, /Prepare exact queued SEO batch/);
assert.match(workflow, /php .*seo_publication_worker\.php.* prepare/);
assert.match(workflow, /Stop cleanly when queue is empty[\s\S]*if: env\.BATCH_STATUS == 'NO_WORK'/);
assert.match(workflow, /Build and package exact desired snapshot[\s\S]*if: env\.BATCH_STATUS == 'PREPARED'/);
assert.match(workflow, /Validate package and run existing deployment engine[\s\S]*if: env\.BATCH_STATUS == 'PREPARED'/);
assert.match(workflow, /TELVORA_SEO_SNAPSHOT_FILE=/);
assert.match(workflow, /RELEASE_SHA="\$GITHUB_SHA"/);
assert.match(workflow, /PACKAGE_SHA256=.*sha256sum/);
assert.match(workflow, /BACKUP_REFERENCE=.*cat/);
assert.doesNotMatch(workflow, /(?:require|cat|readFile)[^\n]*deployment-manifest\.json/);
assert.doesNotMatch(workflow, /RELEASE_SHA[^\n]*deployment-manifest\.json/);
assert.match(workflow, /complete --batch-id=.*--release-sha=\'\$RELEASE_SHA\'/);
assert.match(workflow, /complete --batch-id=.*--backup-reference=\'\$BACKUP_REFERENCE\'/);
assert.match(workflow, /SNAPSHOT_FILE_SHA256/);
assert.match(workflow, /sha256sum[\s\S]*SNAPSHOT_FILE_SHA256/);
assert.doesNotMatch(workflow, /sha256sum[^\n]*SNAPSHOT_HASH/);
assert.match(workflow, /snapshot\.get\('version'\) != 1/);
assert.match(workflow, /snapshot\.get\('batch_id'\) != sys\.argv\[2\]/);
assert.match(workflow, /snapshot\.get\('snapshot_hash'\) != sys\.argv\[3\]/);
assert.match(workflow, /npm run build:seo[\s\S]*npm run seo:package[\s\S]*npm run seo:validate-package/);
assert.match(workflow, /Validate batch immediately before deployment/);
assert.match(workflow, /existing deployment engine/);
assert.match(workflow, /--batch-id=.*--snapshot-hash=/);
assert.match(workflow, /complete --batch-id=/);
assert.match(workflow, /fail --batch-id=/);
assert.match(workflow, /if: failure\(\) && env\.BATCH_STATUS == 'PREPARED'/);
assert.match(workflow, /environment: seo-production/);
assert.match(workflow, /StrictHostKeyChecking=yes/);
assert.match(workflow, /UserKnownHostsFile=/);
assert.match(workflow, /IdentitiesOnly=yes/);
assert.match(worker, /\['prepare', 'validate', 'complete', 'fail'\]/);
assert.match(worker, /seoPublicationValidateBatchStillCurrent/);
assert.match(worker, /seoPublicationBatchComplete/);
assert.match(worker, /seoPublicationBatchFail/);
assert.match(worker, /'release-sha'/);
assert.match(publicationService, /\$finalized = seoPublicationRunTransaction/);
assert.match(publicationService, /SELECT \* FROM seo_publication_jobs WHERE id = :id/);
assert.match(publicationService, /SELECT id, is_active, publication_status, publication_revision FROM products/);
console.log('PASS SEO publication Phase 2C orchestration contract');
