import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
const manifest = JSON.parse(await readFile('seo-artifacts/routes.json', 'utf8'));
const htaccess = await readFile('deployment/seo-stage2/production.htaccess.final', 'utf8');
const generated = await readFile('seo-artifacts/production.htaccess', 'utf8');
const apache = await readFile('seo-artifacts/routes.apache.conf', 'utf8');
const required = [
  'Options -MultiViews',
  'HTTP:X-Forwarded-Proto',
  'HTTP_HOST',
  'https://telvora.ru%{REQUEST_URI}',
  'RewriteRule ^catalog$ _prerender/catalog.html [END]',
  'RewriteRule ^catalog/oled$ _prerender/catalog-oled.html [END]',
  'RewriteRule ^catalog/oled/lg-oled77c5rla$ _prerender/product-lg-oled77c5rla.html [END]',
  'RewriteRule ^(?:checkout|admin|soundbars|accessories)$ client.html [END]',
  'RewriteRule ^order-success/[^/]+$ client.html [END]',
  'RewriteCond %{REQUEST_FILENAME} -f [OR]',
  'RewriteCond %{REQUEST_FILENAME} -d',
  'RewriteCond %{THE_REQUEST}',
  'RewriteRule ^ - [R=404,END]',
  'ErrorDocument 404 /404.html',
];
for (const rule of required) assert.ok(htaccess.includes(rule), `missing final .htaccess rule: ${rule}`);
assert.ok(apache.includes('_prerender/catalog.html'));
assert.ok(apache.includes('THE_REQUEST'));
assert.ok(apache.includes('R=404,END'));
assert.ok(!htaccess.includes('catalog/index.html'));
assert.ok(!htaccess.includes('delivery/index.html'));
for (const route of manifest.routes) {
  const target = route === '/' ? 'RewriteRule ^$ index.html' : `RewriteRule ^${route.slice(1)}$ `;
  assert.ok(generated.includes(target), `generated .htaccess route missing: ${route}`);
}
for (const route of manifest.productRoutes) assert.ok(generated.includes(`RewriteRule ^${route.slice(1)}$ _prerender/product-${route.split('/').pop()}.html [END]`), route);
assert.match(generated, /Generated by build:seo/);
assert.match(generated, /THE_REQUEST/);
assert.match(generated, /R=404,END/);
console.log('seo_htaccess_test: PASS (flat internal routing, no DirectorySlash conflict, real 404)');
