import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import YAML from 'yaml';

const path = '.github/workflows/seo-production-deploy.yml';
const workflow = await readFile(path, 'utf8');
const parsed = YAML.parse(workflow);
assert.equal(parsed.jobs.preflight.environment, 'seo-staging');
assert.equal(parsed.jobs.activation.environment, 'seo-production');
assert.equal(parsed.jobs.activation.needs, 'preflight');
assert.equal(parsed.jobs.preflight.outputs.remote_stage, undefined);
assert.equal(parsed.jobs.preflight.outputs.stage_id, '${{ steps.stage.outputs.stage_id }}');
assert.equal(parsed.jobs.activation.env.STAGE_ID, '${{ needs.preflight.outputs.stage_id }}');
assert.equal(parsed.jobs.preflight.steps.some(step => /Activate production/.test(step.name ?? '')), false);

assert.match(workflow, /^name: SEO Production Deploy/m);
assert.match(workflow, /^\s+workflow_dispatch:/m);
assert.match(workflow, /^\s+preflight:/m);
assert.match(workflow, /^\s+activation:/m);
assert.match(workflow, /^\s+needs: preflight/m);
assert.match(workflow, /^\s+environment: seo-production/m);
assert.match(workflow, /contents:\s*read/);
assert.match(workflow, /group:\s*telvora-seo-production-deploy/);
assert.match(workflow, /release_sha:/);
assert.match(workflow, /confirmation:/);
assert.match(workflow, /DEPLOY TELVORA SEO PRODUCTION/);
assert.match(workflow, /\^\[0-9a-fA-F\]\{40\}\$/);
assert.match(workflow, /ref:\s+\$\{\{\s*inputs\.release_sha\s*\}\}/);
assert.match(workflow, /actual_sha=.*git rev-parse HEAD/);
assert.match(workflow, /test "\$actual_sha" = "\$\{REQUESTED_RELEASE_SHA,,\}"/);
assert.match(workflow, /REMOTE_DOCUMENT_ROOT: \/var\/www\/u3609206\/data\/www\/telvora\.ru/);
assert.match(workflow, /REMOTE_BACKUP_ROOT: \/var\/www\/u3609206\/data\/telvora-backups/);
assert.match(workflow, /remote_stage="\$REMOTE_BASE\/staging\/\$stage_id"/);
assert.match(workflow, /stage_id: \$\{\{ steps\.stage\.outputs\.stage_id \}\}/);
assert.doesNotMatch(workflow, /remote_stage:\s*\$\{\{\s*steps\.stage\.outputs\.remote_stage/);
assert.match(workflow, /echo "stage_id=\$stage_id" >> "\$GITHUB_OUTPUT"/);
assert.doesNotMatch(workflow, /echo "remote_stage=.*GITHUB_OUTPUT/);
assert.match(workflow, /STAGE_ID: \$\{\{ needs\.preflight\.outputs\.stage_id \}\}/);
assert.doesNotMatch(workflow, /REMOTE_STAGE:\s*\$\{\{\s*needs\.preflight\.outputs\.remote_stage/);
assert.match(workflow, /REMOTE_STAGE="\$REMOTE_BASE\/staging\/\$STAGE_ID"/);
assert.match(workflow, /\^telvora-seo-\[0-9a-f\]\{40\}-\[0-9\]\+\$/);
assert.match(workflow, /case "\$STAGE_ID" in "telvora-seo-\$\{REQUESTED_RELEASE_SHA\}-"\*/);
assert.match(workflow, /realpath -m -- "\$stage"/);
assert.match(workflow, /case "\$canonical_stage" in \/var\/www\/u3609206\/data\/staging\/\*/);
assert.match(workflow, /case "\$canonical_stage" in "\$document"\|"\$document"\/\*/);
assert.match(workflow, /test -s "\$RUNNER_TEMP\/activation-plan\.json"/);
assert.match(workflow, /activation plan is unexpectedly empty/);
assert.match(workflow, /activation plan is missing required list fields/);
assert.match(workflow, /StrictHostKeyChecking=yes/);
assert.match(workflow, /UserKnownHostsFile="\$SSH_DIR\/known_hosts"/);
assert.match(workflow, /IdentitiesOnly=yes/);
assert.doesNotMatch(workflow, /ssh-keyscan/);
assert.doesNotMatch(workflow, /StrictHostKeyChecking=no/);
assert.match(workflow, /--dry-run/);
assert.match(workflow, /--rollback/);
assert.match(workflow, /Fetch exact dry-run plan for human review/);
assert.match(workflow, /Actual mutation plan/);
assert.match(workflow, /\('add', 'ADD'\)/);
assert.match(workflow, /\('replace', 'REPLACE'\)/);
assert.match(workflow, /\('remove', 'REMOVE'\)/);
assert.match(workflow, /ACTIVATION ORDER:/);
assert.match(workflow, /PROTECTED \/ PRESERVED:/);
assert.match(workflow, /- \(none\)/);
assert.match(workflow, /test "\$plan_ok" -eq 1/);
assert.match(workflow, /PRODUCTION ACTIVATION: NOT PERFORMED/);
assert.match(workflow, /sha256sum/);
assert.match(workflow, /test "\$manifest_commit" = "\$\{REQUESTED_RELEASE_SHA,,\}"/);
assert.match(workflow, /prohibited production mutation in plan/);
assert.match(workflow, /uploads\/.*pdf\/.*telegram/);
assert.match(workflow, /FAIL_ROLLED_BACK/);
assert.match(workflow, /yandex_2f15c7f5db6e96d5\.html/);
assert.match(workflow, /PRODUCTION_ACTIVATION_RESULT=PERFORMED/);
assert.match(workflow, /PRODUCTION_ACTIVATION_RESULT=ROLLED_BACK/);
assert.match(workflow, /if: always\(\)/);
assert.doesNotMatch(workflow, /rm\s+-rf\s+--?\s*"\$REMOTE_DOCUMENT_ROOT/);
assert.doesNotMatch(workflow, /rsync[^\n]*--delete[^\n]*REMOTE_DOCUMENT_ROOT/);
assert.match(workflow, /PRODUCTION ACTIVATION: \$activation/);

console.log('seo_production_workflow_test: PASS');
