import { useEffect,useMemo,useState } from 'react';
import { Wrench,ScanLine,Settings2,Plus,Loader2 } from 'lucide-react';
import { useCart } from '@/store/cart';
import { fetchServices,screenSizeNumber,serviceFits } from '@/services/serviceCatalogService';
import type { ServiceCatalogItem } from '@/types';
import { formatPrice } from '@/lib/format';
const groups=[['mounting','Монтаж'],['pixel_test','Пиксель-тест'],['other','Другие услуги']] as const;
const icons={mounting:Wrench,pixel_test:ScanLine,other:Settings2};
export default function ServicesPage(){
 const {items,services,addService}=useCart();const [catalog,setCatalog]=useState<ServiceCatalogItem[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [size,setSize]=useState<number|''>('');
 useEffect(()=>{fetchServices().then(setCatalog).catch(e=>setError(e.message)).finally(()=>setLoading(false))},[]);
 const shown=useMemo(()=>size===''?catalog:catalog.filter(s=>serviceFits(s,size)),[catalog,size]);
 return <main className="min-h-screen bg-graphite-50 dark:bg-graphite-950 py-28 sm:py-36"><div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8"><header className="max-w-3xl mb-10"><span className="text-sm font-semibold uppercase tracking-widest text-accent-500">Помощь специалистов</span><h1 className="mt-3 font-display text-4xl sm:text-5xl font-extrabold">Сервисные услуги</h1><p className="mt-5 text-lg text-graphite-600 dark:text-graphite-300">Выберите услугу для конкретного телевизора в корзине. Стоимость фиксируется сервером при оформлении заказа.</p></header><label className="block max-w-xs mb-10 text-sm font-semibold">Диагональ телевизора<select value={size} onChange={e=>setSize(e.target.value===''?'':Number(e.target.value))} className="mt-2 w-full rounded-xl border border-graphite-200 dark:border-white/10 bg-white dark:bg-graphite-900 px-4 py-3"><option value="">Все диагонали</option>{[32,43,55,65,75,77,83,86,87,98].map(v=><option key={v}>{v}</option>)}</select></label>{loading&&<Loader2 className="animate-spin text-accent-500"/>}{error&&<p role="alert" className="text-red-500">{error}</p>}{groups.map(([key,title])=>{const list=shown.filter(s=>s.category===key);if(!list.length)return null;const Icon=icons[key];return <section key={key} className="mb-12"><h2 className="font-display text-2xl font-bold mb-5">{title}</h2><div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-5">{list.map(service=>{const compatible=items.filter(item=>serviceFits(service,screenSizeNumber(item.screenSize)));return <article key={service.id} className="flex flex-col rounded-3xl border border-graphite-200 dark:border-white/10 bg-white dark:bg-graphite-900 p-6"><div className="w-11 h-11 rounded-2xl bg-accent-500/15 flex items-center justify-center mb-4"><Icon className="w-5 h-5 text-accent-500"/></div><h3 className="font-display text-lg font-bold">{service.name}</h3><p className="mt-1 text-sm font-semibold text-accent-500">{service.min_screen_size===null?'Для совместимого телевизора':`${service.min_screen_size}–${service.max_screen_size}″`}</p><p className="mt-3 text-sm text-graphite-600 dark:text-graphite-300 flex-1">{service.description}</p><p className="mt-5 font-bold">{service.price===null?'Стоимость уточняется':formatPrice(service.price)}</p>{service.price!==null&&<div className="mt-4 space-y-2">{compatible.length?compatible.map(tv=>{const exists=services.some(s=>s.serviceId===service.id&&s.targetCartItemId===tv.id);return <button key={tv.id} disabled={exists} onClick={()=>addService(service,tv)} className="w-full inline-flex items-center justify-center gap-2 rounded-xl bg-accent-500 px-3 py-2.5 text-sm font-semibold text-white disabled:opacity-50"><Plus className="w-4 h-4"/>{exists?'Добавлено':`Добавить для ${screenSizeNumber(tv.screenSize)}″`}</button>}):<p className="text-xs text-graphite-500">Добавьте совместимый телевизор в корзину</p>}</div>}</article>})}</div></section>})}</div></main>}
