CREATE TABLE service_catalog (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    service_key VARCHAR(80) NOT NULL,
    category VARCHAR(32) NOT NULL,
    name VARCHAR(180) NOT NULL,
    description VARCHAR(500) NOT NULL,
    min_screen_size SMALLINT UNSIGNED NULL,
    max_screen_size SMALLINT UNSIGNED NULL,
    price DECIMAL(12,2) NULL,
    is_active TINYINT(1) NOT NULL DEFAULT 1,
    sort_order INT NOT NULL DEFAULT 0,
    requires_tv TINYINT(1) NOT NULL DEFAULT 1,
    metadata JSON NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_service_catalog_key (service_key),
    KEY idx_service_catalog_public (is_active, category, sort_order),
    CONSTRAINT chk_service_catalog_range CHECK (min_screen_size IS NULL OR max_screen_size IS NULL OR min_screen_size <= max_screen_size),
    CONSTRAINT chk_service_catalog_price CHECK (price IS NULL OR price >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE order_services (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    order_id INT UNSIGNED NOT NULL,
    order_item_id INT UNSIGNED NOT NULL,
    service_id BIGINT UNSIGNED NULL,
    service_key VARCHAR(80) NOT NULL,
    service_name VARCHAR(180) NOT NULL,
    service_category VARCHAR(32) NOT NULL,
    television_name VARCHAR(255) NOT NULL,
    screen_size SMALLINT UNSIGNED NOT NULL,
    unit_price DECIMAL(12,2) NOT NULL,
    quantity INT UNSIGNED NOT NULL DEFAULT 1,
    total DECIMAL(12,2) NOT NULL,
    metadata JSON NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    KEY idx_order_services_order (order_id),
    KEY idx_order_services_order_item (order_item_id),
    KEY idx_order_services_service (service_id),
    CONSTRAINT fk_order_services_order FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE RESTRICT,
    CONSTRAINT fk_order_services_order_item FOREIGN KEY (order_item_id) REFERENCES order_items(id) ON DELETE RESTRICT,
    CONSTRAINT fk_order_services_catalog FOREIGN KEY (service_id) REFERENCES service_catalog(id) ON DELETE SET NULL,
    CONSTRAINT chk_order_services_quantity CHECK (quantity > 0),
    CONSTRAINT chk_order_services_price CHECK (unit_price >= 0 AND total = unit_price * quantity)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO service_catalog (service_key, category, name, description, min_screen_size, max_screen_size, price, sort_order, requires_tv, metadata) VALUES
('wall-mount-27-42','mounting','Монтаж телевизора на стену','Монтаж телевизора на подготовленное место. Крепление и дополнительные работы согласовываются отдельно.',27,42,5000,10,1,JSON_OBJECT('pricing_status','confirmed')),
('wall-mount-43-55','mounting','Монтаж телевизора на стену','Монтаж телевизора на подготовленное место. Крепление и дополнительные работы согласовываются отдельно.',43,55,7000,20,1,JSON_OBJECT('pricing_status','confirmed')),
('wall-mount-56-65','mounting','Монтаж телевизора на стену','Монтаж телевизора на подготовленное место. Крепление и дополнительные работы согласовываются отдельно.',56,65,10000,30,1,JSON_OBJECT('pricing_status','confirmed')),
('wall-mount-66-77','mounting','Монтаж телевизора на стену','Монтаж телевизора на подготовленное место. Крепление и дополнительные работы согласовываются отдельно.',66,77,12000,40,1,JSON_OBJECT('pricing_status','confirmed')),
('wall-mount-78-85','mounting','Монтаж телевизора на стену','Монтаж телевизора на подготовленное место. Крепление и дополнительные работы согласовываются отдельно.',78,85,15000,50,1,JSON_OBJECT('pricing_status','confirmed')),
('wall-mount-86-98','mounting','Монтаж телевизора на стену','Монтаж телевизора на подготовленное место. Крепление и дополнительные работы согласовываются отдельно.',86,98,35000,60,1,JSON_OBJECT('pricing_status','confirmed')),
('pixel-test-32-54','pixel_test','Проверка телевизора на битые пиксели','Проверка экрана на дефектные пиксели перед передачей телевизора.',32,54,3000,110,1,JSON_OBJECT('pricing_status','confirmed')),
('pixel-test-55-64','pixel_test','Проверка телевизора на битые пиксели','Проверка экрана на дефектные пиксели перед передачей телевизора.',55,64,4000,120,1,JSON_OBJECT('pricing_status','confirmed')),
('pixel-test-65-74','pixel_test','Проверка телевизора на битые пиксели','Проверка экрана на дефектные пиксели перед передачей телевизора.',65,74,6000,130,1,JSON_OBJECT('pricing_status','confirmed')),
('pixel-test-75-82','pixel_test','Проверка телевизора на битые пиксели','Проверка экрана на дефектные пиксели перед передачей телевизора.',75,82,7000,140,1,JSON_OBJECT('pricing_status','confirmed')),
('pixel-test-83-86','pixel_test','Проверка телевизора на битые пиксели','Проверка экрана на дефектные пиксели перед передачей телевизора.',83,86,8000,150,1,JSON_OBJECT('pricing_status','confirmed')),
('pixel-test-87-120','pixel_test','Проверка телевизора на битые пиксели','Проверка экрана на дефектные пиксели перед передачей телевизора.',87,120,13000,160,1,JSON_OBJECT('pricing_status','confirmed')),
('tv-setup','other','Настройка телевизора','Первичная настройка изображения, сети и основных функций после согласования состава работ.',NULL,NULL,NULL,210,1,JSON_OBJECT('pricing_status','quote_required'));
