const escape = value => value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');

export const managedRootFiles = [
  'index.html', 'client.html', '404.html', 'robots.txt', 'sitemap.xml',
  'favicon.ico', 'favicon.svg', 'favicon-32x32.png', 'favicon-48x48.png',
  'apple-touch-icon.png', 'telvora-logo.svg', 'telvora-logo-dark.svg',
  'telvora-logo-white.svg', 'telvora-mark.svg',
];
export const managedDirectories = ['assets', 'images', '_prerender'];
export const clientRoutePatterns = ['checkout', 'admin', 'soundbars', 'accessories'];

export function generateProductionHtaccess({ routes, productRoutes = [], prerenderFiles }) {
  const slashRules = routes.filter(path => path !== '/').map(path =>
    `RewriteRule ^${escape(path.slice(1))}/$ https://telvora.ru${path} [R=301,L,NE]`);
  const prerenderRules = routes.map(path =>
    `RewriteRule ^${path === '/' ? '$' : escape(path.slice(1)) + '$'} ${path === '/' ? 'index.html' : prerenderFiles[path].slice(1)} [END]`);
  const productComment = productRoutes.length ? `# Active product routes: ${productRoutes.join(', ')}` : '# Active product routes: none';
  return `# Generated by build:seo. Do not edit manually.\n# Route inventory is derived from the public API snapshot.\n\nOptions -MultiViews\nRewriteEngine On\n\nRewriteCond %{HTTP:X-Forwarded-Proto} !https [OR]\nRewriteCond %{HTTP_HOST} ^www\\.telvora\\.ru$ [NC]\nRewriteRule ^ https://telvora.ru%{REQUEST_URI} [R=301,L,NE]\n\nRewriteRule ^televisions/?$ https://telvora.ru/catalog [R=301,L,NE]\n${slashRules.join('\n')}\n\n${productComment}\n# Internal prerender files are never a public alternative URL.\nRewriteCond %{THE_REQUEST} \\s/+_prerender(?:[/\\s?]) [NC]\nRewriteRule ^_prerender(?:/|$) - [R=404,END]\n\n# Known prerendered public routes.\n${prerenderRules.join('\n')}\n\n# Client-only routes remain direct-loadable but noindex.\nRewriteRule ^(?:${clientRoutePatterns.join('|')})$ client.html [END]\nRewriteRule ^order-success/[^/]+$ client.html [END]\n\n# Preserve real files/directories, including PHP, assets, uploads and ACME.\nRewriteCond %{REQUEST_FILENAME} -f [OR]\nRewriteCond %{REQUEST_FILENAME} -d\nRewriteRule ^ - [END]\n\n# Unknown routes are real HTTP 404 responses.\nRewriteRule ^ - [R=404,END]\nErrorDocument 404 /404.html\n`;
}

export function routeInventoryFromManifest(manifest) {
  return { routes: manifest.routes, productRoutes: manifest.productRoutes, prerenderFiles: manifest.prerenderFiles };
}
